query Coco_BountiesPage($login: String!, $status: String!) {
  user(login: $login) {
    bountiesPage(status: $status, first: 20) {
      edges {
        node {
          id
          campaign {
            id
            title
            boxArtURL
            game {
              boxArtURL(width: 85, height: 113)
            }
          }
          status
          expiresAt
          maximumPayoutCents
          payoutCents
        }
      }
    }
  }
}
