query Coco_BountiesPage($login: String!, $status: String!, $first: Int!) {
  user(login: $login) {
    bountiesPage(status: $status, first: $first) {
      edges {
        node {
          id
          status
          expiresAt
          maximumPayoutCents
          trackingStoppedAt
          payoutCents

          campaign {
            id
            title
            sponsor
            displayName
            boxArtURL
            endTime

            game {
              displayName
              boxArtURL(width: 85, height: 113)
            }
          }
        }
      }
    }
  }
}
