query Coco_SponsorshipInstances($creatorID: ID!, $query: SponsorshipInstanceQuery, $first: Int, $after: Cursor) {
  sponsorshipInstances(creatorID: $creatorID, query: $query, first: $first, after: $after) {
    edges {
      node {
        id
        state
        acceptBy
        description

        advertiser {
          name

          imageAsset {
            lightModeURL
            darkModeURL
          }
        }

        self {
          paymentActual {
            ...money
          }

          paymentPotential {
            ...money
          }
        }
      }
    }
  }
}

fragment money on Money {
  currencyCode
  minorUnits
  amount
}
