query Coco_Sponsorships($query: SponsorshipInstanceQuery) {
  sponsorshipInstances(query: $query) {
    edges {
      node {
        id
        state
        acceptBy
        description

        advertiser {
          name

          imageAsset {
            lightModeURL
            darkModeURL
          }
        }

        self {
          paymentActual {
            ...money
          }

          paymentPotential {
            ...money
          }
        }
      }
    }
  }
}

fragment money on Money {
  currencyCode
  minorUnits
  amount
}
