query Coco_ThirdPartySponsorshipOffers($first: Int, $after: Cursor) {
  thirdPartySponsorshipOffers(first: $first, after: $after) {
    edges {
      node {
        brandName
        brandImageURL
        thirdPartyBrokerOfferURL
        description

        basePay {
          ...money
        }

        averageEarningsPerConvertedUser {
          ...money
        }
      }
    }
  }
}

fragment money on Money {
  currencyCode
  minorUnits
  amount
}
