query Coco_ThirdPartySponsorships($first: Int!) {
  thirdPartySponsorshipOffers(first: $first) {
    edges {
      node {
        brandName
        brandImageURL
        thirdPartyBrokerOfferURL
        description

        basePay {
          ...money
        }

        averageEarningsPerConvertedUser {
          ...money
        }
      }
    }
  }
}

fragment money on Money {
  currencyCode
  minorUnits
  amount
}
