name: Release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest

    outputs:
      created: ${{ steps.release.outputs.release_created }}
      version: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - id: release
        name: Release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple

  submit:
    name: Submit
    runs-on: ubuntu-latest

    needs:
      - release-please

    if: github.event_name == 'workflow_dispatch' || needs.release-please.outputs.created

    strategy:
      fail-fast: false
      matrix:
        platform:
          - chrome
          - firefox

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build:${{ matrix.platform }}

      - name: Update Manifest
        run: npx dot-json@1 dist/manifest.json version ${{ needs.release-please.outputs.version }}

      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARCHIVE_NAME: ${{ github.event.repository.name }}-${{ matrix.platform }}-${{ needs.release-please.outputs.version }}.zip
        run: cd dist && zip -r $ARCHIVE_NAME . && gh release upload ${{ needs.release-please.outputs.tag_name }} $ARCHIVE_NAME

      - name: Submit
        run: |
          case ${{ matrix.platform }} in
            chrome)
              cd dist && npx chrome-webstore-upload-cli
              ;;
            firefox)
              cd dist && npx web-ext sign --channel listed
              ;;
          esac
        env:
          CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          EXTENSION_ID: ${{ secrets.GOOGLE_EXTENSION_ID }}
          REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
