name: Test

on:
  - pull_request
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: npm ci

      - name: Test
        run: npm test

  build:
    name: Build
    runs-on: ubuntu-latest

    needs:
      - test

    strategy:
      fail-fast: false
      matrix:
        platform:
          - chrome
          - firefox

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: npm install

      - name: Build
        run: npm run build:${{ matrix.platform }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-artifact
          path: dist
